lang = {
    'en': {
        ':title' : 'Presale Is Live',
        ':menu-home': 'Home',
        ':menu-why-choose-us': 'Why Choose Us?',
        ':menu-token-details': 'Token Details',
        ':whitepaper': 'Whitepaper',
        ':connect-wallet': 'Connect Wallet',
        ':connect': 'Connect Wallet',
        ':apresentation-h5': 'Join the Presale',
        ':apresentation-h1': 'Invest in the Future of Ai Technology with Cellesti',
        ':apresentation-h7': 'Invest easily in AI startups with fractional tokens and be part of the next tech revolution.',
        ':apresentation-paragraph-1': 'AI powered investments support some of the promising AI Startups across the globe.',
        ':apresentation-paragraph-2': 'Fractional NFTs: Invest according to your budget and receive ownership in exciting whitepaper ventures.',
        ':alert-copy-mail': 'Email copied!',
        ':alert-copy-mail-2': 'Email copied!',
        ':alert-copy-mail-3': 'Email copied!',
        ':buy-cellesti-token': 'Buy Cellesti Token',
        ':stage': 'Stage 1',
        ':next-stage-value': '1 CLLS = $0.007 & Next Stage = $0.00875',
        ':tokens-sold': 'TOKENS SOLD',
        ':usd-raised': 'USD RAISED',
        ':bonus': 'Bonus',
        ':payment-method': 'Payment Method',
        ':buy-with-eth': 'BUY WITH ETH',
        ':buy-with-usdt': 'BUY WITH USDT',
        ':choose': 'en',
        ':how-to-buy': 'How to Buy?',
        ':buy-button': 'Buy',
        ':buy-button-2': 'Buy',
        ':buy-button-3': 'Buy',
        ':approve': 'Approve',
        ':clls-token': 'THE $CLLS TOKEN',
        ':clls-token-paragraph-1': 'Cellesti is a groundbreaking platform that enables investments in AI startups using $CLLS, our innovative cryptocurrency. Through our fractional investment system, we offer the chance to support promising AI startups via NFTs (Non-Fungible Tokens), turning each opportunity into a unique digital asset.',
        ':clls-token-paragraph-2': 'This allows you to invest according to your financial capacity, while enjoying the advantages of being an early supporter of emerging technologies. Cellesti makes investing simple, secure, and impactful, giving you the opportunity to actively participate in tech innovation and reap the rewards as an early investor.',
        ':why-choose-us-card-1-title': 'Effortless Investment',
        ':why-choose-us-card-1-text': 'Investing in cutting-edge AI startups has never been more accessible. With our seamless and intuitive platform, anyone—whether you\'re an experienced investor or just starting out—can easily navigate and start investing in the future of AI technology.',
        ':why-choose-us-card-2-title': 'Advanced Security',
        ':why-choose-us-card-2-text': 'Your trust and security are our top priorities at Cellesti. We use advanced blockchain technology to keep your investments safe, with top-level encryption and decentralized systems that ensure a highly secure environment.',
        ':why-choose-us-card-3-title': 'Revolutionizing Investment',
        ':why-choose-us-card-3-text': 'Unlock new opportunities with our fractional investment system, gaining ownership in previously inaccessible AI startups through innovative NFT tokenization.',
        ':why-choose-us-card-4-title': 'Expansive Investment Opportunities',
        ':why-choose-us-card-4-text': 'Expand your investment scope by easily diversifying your AI portfolio. Discover startups at every stage and align your investments with your financial goals with ease.',
        ":why-choose-us-card-5-title": "Pioneering Rewards for Early Supporters",
        ":why-choose-us-card-5-text": "Be a pioneer in tech innovation, enjoying exclusive benefits and insights as an early supporter, setting the stage for potential future gains.",
        ":why-choose-us-card-6-title": "Stay Ahead with Live Monitoring",
        ":why-choose-us-card-6-text": "Use our simple dashboard to monitor your investments in real time. Make strategic decisions in the rapidly evolving AI sector.",
        ":ai-action-title": "JOIN OUR COMMUNITY",
        ":ai-action-subtitle": "Smart Finance With Cellesti",
        ":ai-action-descript": "Join our project, driven by innovation, community, and our AI vision. Buy, sell, and swap easily in our decentralized ecosystem. Become a member of our AI community.",
        ":read-more": "Read more",
        ":powered-by": "Powered By:",
        ":claim-your-tokens": "CLAIM YOUR TOKENS",
        ":see-tokens-button": "See Your Claimable Tokens",
        ":claimable-tokens": "Claimable Tokens",
        ":bonus-tokens": "Bonus Tokens",
        ":staking-text": "By staking $CLLS tokens, investors can earn rewards from our 10% sell tax, which is allocated to a dedicated reward pool. The staking mechanism offers a unique opportunity for our community to earn $CLLS token rewards while helping drive the growth of AI technology startups.",
        ":percents-text-1": "Public Sale",
        ":percents-text-2": "Development Team",
        ":percents-text-lock": "3 years locked",
        ":percents-text-3": "LP + Exchange Listing + Reward Pool",
        ":percents-text-5": "Legal & Advisors",
        ":notebook-title": "GOVERNANCE",
        ":notebook-text": "The $CLLS token empowers holders to actively participate in the platform's decision-making. By proposing, discussing, and voting on key issues, they help shape the platform’s future. This community-driven approach supports the growth of AI startups while promoting a more collaborative ecosystem.",
        ":giveaway-title": "JOIN THE GIVEAWAY!",
        ":giveaway-text-part-a": "Ready to win big? Participate in the great",
        ":giveaway-text-part-b": "Tesla Model S Giveaway",
        ":giveaway-text-part-c": "Participate and complete all entries for your chance to win the grand prize. Don't miss your chance to be the lucky winner!",
        ":giveaway-button": "LET'S PLAY RAFFLE",
        ":ai-startups-title": "AI START-UPS APPLY",
        ":ai-startups-text-1": "Are you an AI start-up looking to raise funds and engage with your community?",
        ":ai-startups-text-2": "Our NFT marketplace offers an innovative platform for minting investment opportunities, connecting a dedicated community of investors committed to advancing AI technology. Through this marketplace, investors can access unique investment options while supporting the growth and development of cutting-edge AI startups.",
        ":ai-startups-buttons-apply": "Apply",
        ":ai-startups-buttons-buy": "Buy $CLLS",
        ":faqs-title": "You may have questions, we have the answers.",
        ":faq-heading-1": "What is Cellesti TOKEN?",
        ":faq-text-1": "Cellesti is a crypto crowdfunding NFT platform that allows users to invest in AI start-up projects using Fiat and Crypto. The NFT marketplace enables start-ups to raise funds and engage with their community by offering reward and equity-based NFTs.",
        ":faq-heading-2": "How do I purchase Cellesti token from presale?",
        ":faq-text-2": "$CLLS tokens can be purchased during the presale period through the Cellesti website using ETH, USDT, BTC, and many more supported cryptocurrencies.",
        ":faq-heading-3": "Which Blockchain network is Cellesti token on?",
        ":faq-text-3": "Cellesti is built on the Ethereum (ETH), leveraging its speed, usability, and compatibility with decentralized applications to create a seamless user experience.",
        ":faq-heading-4": "How do I claim my Tokens?",
        ":faq-text-4": "Once the presale ends, you just need to connect your wallet and press the claim button. Once the transaction is complete, import the Cellesti token address into your wallet and you’ll be able to see your tokens.",
        ":faq-heading-5": "How can I store and manage my Cellesti tokens?",
        ":faq-text-5": "Cellesti tokens can be stored and managed in compatible cryptocurrency wallets. We recommend using wallets that support Ethereum, such as MetaMask or Trust Wallet.",
        ':copyright': "Copyright © 2024. All rights reserved by Cellesti.",
        ':disclaimer-title': "Disclaimer",
        ':disclaimer-text': "Cryptocurrency investments carry a high risk of volatility. Be aware of the tax implications, as profits may be subject to capital gains or other taxes in your jurisdiction. Cryptocurrency regulations can vary, so ensure you understand the rules in your area. Conduct thorough research and invest only what you can afford to lose.",
        ':our-socials-title': "Our socials"
    },
    'pt': {
        ':title' : 'Pré-venda Está Ao Vivo',
        ':menu-home': 'Início',
        ':menu-why-choose-us': 'Por que nos escolher?',
        ':menu-token-details': 'Detalhes do Token',
        ':whitepaper': 'Documento Técnico',
        ':connect-wallet': 'Conectar Carteira',
        ':connect': 'Conectar Carteira',
        ':apresentation-h5': 'Junte-se à Pré-venda',
        ':apresentation-h1': 'Invista no Futuro da Tecnologia de IA com a Cellesti',
        ':apresentation-h7': 'Invista facilmente em startups de IA com tokens fracionários e faça parte da próxima revolução tecnológica.',
        ':apresentation-paragraph-1': 'Investimentos impulsionados por IA apoiam algumas das promissoras startups de IA em todo o mundo.',
        ':apresentation-paragraph-2': 'NFTs fracionários: Invista de acordo com seu orçamento e receba propriedade em empolgantes empreendimentos do whitepaper.',
        ':alert-copy-mail': 'E-mail copiado!',
        ':alert-copy-mail-2': 'E-mail copiado!',
        ':alert-copy-mail-3': 'E-mail copiado!',
        ':buy-cellesti-token': 'Comprar Token Cellesti',
        ':stage': 'Etapa 1',
        ':next-stage-value': '1 CLLS = $0,007 e Próxima Etapa = $0,00875',
        ':tokens-sold': 'TOKENS VENDIDOS',
        ':usd-raised': 'USD ARRECADADOS',
        ':bonus': 'Bônus',
        ':payment-method': 'Método de Pagamento',
        ':buy-with-eth': 'COMPRAR COM ETH',
        ':buy-with-usdt': 'COMPRAR COM USDT',
        ':choose': 'pt',
        ':how-to-buy': 'Como Comprar?',
        ':buy-button': 'Comprar',
        ':buy-button-2': 'Comprar',
        ':buy-button-3': 'Comprar',
        ':approve': 'Aprovar',
        ':clls-token': 'O TOKEN $CLLS',
        ':clls-token-paragraph-1': 'Cellesti é uma plataforma inovadora que possibilita investimentos em startups de IA usando $CLLS, nossa criptomoeda inovadora. Através de nosso sistema de investimento fracionário, oferecemos a chance de apoiar startups promissoras de IA por meio de NFTs (Tokens Não Fungíveis), transformando cada oportunidade em um ativo digital exclusivo.',
        ':clls-token-paragraph-2': 'Isso permite que você invista de acordo com sua capacidade financeira, enquanto aproveita as vantagens de ser um apoiador inicial de tecnologias emergentes. A Cellesti torna o investimento simples, seguro e impactante, dando a você a oportunidade de participar ativamente da inovação tecnológica e colher os frutos como um investidor inicial.',
        ':why-choose-us-card-1-title': 'Investimento Sem Esforço',
        ':why-choose-us-card-1-text': 'Investir em startups de IA de ponta nunca foi tão acessível. Com nossa plataforma intuitiva e sem costura, qualquer um—seja você um investidor experiente ou esteja apenas começando—pode navegar facilmente e começar a investir no futuro da tecnologia de IA.',
        ':why-choose-us-card-2-title': 'Segurança Avançada',
        ':why-choose-us-card-2-text': 'Sua confiança e segurança são nossas principais prioridades na Cellesti. Usamos tecnologia de blockchain avançada para manter seus investimentos seguros, com criptografia de alto nível e sistemas descentralizados que garantem um ambiente altamente seguro.',
        ':why-choose-us-card-3-title': 'Revolucionando o Investimento',
        ':why-choose-us-card-3-text': 'Desbloqueie novas oportunidades com nosso sistema de investimento fracionário, adquirindo propriedade em startups de IA anteriormente inacessíveis por meio da tokenização inovadora de NFTs.',
        ':why-choose-us-card-4-title': 'Oportunidades de Investimento Expansivas',
        ':why-choose-us-card-4-text': 'Amplie seu escopo de investimento diversificando facilmente seu portfólio de IA. Descubra startups em todos os estágios e alinhe seus investimentos com seus objetivos financeiros com facilidade.',
        ":why-choose-us-card-5-title": "Recompensas Pioneiras para Apoio Inicial",
        ":why-choose-us-card-5-text": "Seja um pioneiro na inovação tecnológica, desfrutando de benefícios e insights exclusivos como um apoiador inicial, preparando o terreno para potenciais ganhos futuros.",
        ":why-choose-us-card-6-title": "Mantenha-se à Frente com Monitoramento Ao Vivo",
        ":why-choose-us-card-6-text": "Use nosso painel simples para monitorar seus investimentos em tempo real. Tome decisões estratégicas no setor de IA em rápida evolução.",
        ":ai-action-title": "Junte-se à Nossa Comunidade",
        ":ai-action-subtitle": "Finanças Inteligentes Com a Cellesti",
        ":ai-action-descript": "Junte-se ao nosso projeto, impulsionado pela inovação, comunidade e nossa visão de IA. Compre, venda e troque facilmente em nosso ecossistema descentralizado. Torne-se um membro da nossa comunidade de IA.",
        ":read-more": "Leia mais",
        ":powered-by": "Powered By:",
        ":claim-your-tokens": "RECLAME SEUS TOKENS",
        ":see-tokens-button": "Veja Seus Tokens Reclamáveis",
        ":claimable-tokens": "Tokens Reclamáveis",
        ":bonus-tokens": "Tokens Bônus",
        ":staking-text": "Ao staking tokens $CLLS, os investidores podem ganhar recompensas a partir de nosso imposto de venda de 10%, que é alocado a um fundo de recompensas dedicado. O mecanismo de staking oferece uma oportunidade única para nossa comunidade ganhar recompensas em tokens $CLLS enquanto ajuda a impulsionar o crescimento de startups de tecnologia em IA.",
        ":percents-text-1": "Venda Pública",
        ":percents-text-2": "Equipe de Desenvolvimento",
        ":percents-text-lock": "3 anos bloqueados",
        ":percents-text-3": "LP + Listagem em Exchanges + Fundo de Recompensas",
        ":percents-text-5": "Jurídico e Consultores",
        ":notebook-title": "GOVERNANÇA",
        ":notebook-text": "O token $CLLS capacita os detentores a participar ativamente da tomada de decisões da plataforma. Ao propor, discutir e votar em questões chave, eles ajudam a moldar o futuro da plataforma. Essa abordagem orientada pela comunidade apoia o crescimento de startups de IA enquanto promove um ecossistema mais colaborativo.",
        ":giveaway-title": "PARTICIPE DO SORTEIO!",
        ":giveaway-text-part-a": "Pronto para ganhar muito? Participe do grande",
        ":giveaway-text-part-b": "Sorteio do Tesla Model S",
        ":giveaway-text-part-c": "Participe e complete todas as inscrições para ter a chance de ganhar o grande prêmio. Não perca a sua chance de ser o sortudo vencedor!",
        ":giveaway-button": "VAMOS AO SORTEIO",
        ":ai-startups-title": "START-UPS DE IA APLICAM",
        ":ai-startups-text-1": "Você é uma startup de IA procurando levantar fundos e se envolver com sua comunidade?",
        ":ai-startups-text-2": "Nosso marketplace de NFTs oferece uma plataforma inovadora para criar oportunidades de investimento, conectando uma comunidade dedicada de investidores comprometidos em avançar a tecnologia de IA. Através deste marketplace, os investidores podem acessar opções de investimento únicas enquanto apoiam o crescimento e desenvolvimento de startups de IA de ponta.",
        ":ai-startups-buttons-apply": "Aplicar",
        ":ai-startups-buttons-buy": "Comprar $CLLS",
        ":faqs-title": "Você pode ter perguntas, nós temos as respostas.",
        ":faq-heading-1": "O que é o TOKEN Cellesti?",
        ":faq-text-1": "Cellesti é uma plataforma de crowdfunding NFT de criptomoeda que permite aos usuários investir em projetos de startups de IA usando Fiat e Cripto. O marketplace de NFTs permite que startups arrecadem fundos e se envolvam com sua comunidade, oferecendo NFTs baseados em recompensas e ações.",
        ":faq-heading-2": "Como compro o token Cellesti na pré-venda?",
        ":faq-text-2": "Os tokens $CLLS podem ser adquiridos durante o período de pré-venda através do site da Cellesti usando ETH, USDT, BTC e muitas outras criptomoedas suportadas.",
        ":faq-heading-3": "Em qual rede Blockchain está o token Cellesti?",
        ":faq-text-3": "Cellesti é construído na Ethereum (ETH), aproveitando sua velocidade, usabilidade e compatibilidade com aplicativos descentralizados para criar uma experiência do usuário fluida.",
        ":faq-heading-4": "Como reivindico meus tokens?",
        ":faq-text-4": "Assim que a pré-venda terminar, você só precisa conectar sua carteira e pressionar o botão de reivindicação. Assim que a transação for concluída, importe o endereço do token Cellesti em sua carteira e você poderá ver seus tokens.",
        ":faq-heading-5": "Como posso armazenar e gerenciar meus tokens Cellesti?",
        ":faq-text-5": "Os tokens Cellesti podem ser armazenados e gerenciados em carteiras de criptomoedas compatíveis. Recomendamos o uso de carteiras que suportem Ethereum, como MetaMask ou Trust Wallet.",
        ':copyright': "Direitos autorais © 2024. Todos os direitos reservados pela Cellesti.",
        ':disclaimer-title': "Isenção de responsabilidade",
        ':disclaimer-text': "Os investimentos em criptomoedas apresentam um alto risco de volatilidade. Esteja ciente das implicações fiscais, pois os lucros podem estar sujeitos a impostos sobre ganhos de capital ou outros impostos em sua jurisdição. As regulamentações de criptomoedas podem variar, então certifique-se de entender as regras em sua área. Realize uma pesquisa completa e invista apenas o que você pode se dar ao luxo de perder.",
        ':our-socials-title': "Nossas redes sociais"
    },
    'fr': {
        ':title' : 'La Prévente Est En Direct',
        ':menu-home': 'Maison',
        ':menu-why-choose-us': 'Pourquoi nous choisir ?',
        ':menu-token-details': 'Détails du Jeton',
        ':whitepaper': 'Livre Blanc',
        ':connect-wallet': 'Connecter le Portefeuille',
        ':connect': 'Connecter le Portefeuille',
        ':apresentation-h5': 'Rejoignez la Prévente',
        ':apresentation-h1': 'Investissez dans l\'avenir de la technologie AI avec Cellesti',
        ':apresentation-h7': 'Investissez facilement dans des startups d\'IA avec des jetons fractionnaires et participez à la prochaine révolution technologique.',
        ':apresentation-paragraph-1': 'Les investissements alimentés par l\'IA soutiennent certaines des startups d\'IA prometteuses à travers le monde.',
        ':apresentation-paragraph-2': 'NFTs fractionnaires : Investissez selon votre budget et recevez une part de propriété dans des projets passionnants du livre blanc.',
        ':alert-copy-mail': 'E-mail copié !',
        ':alert-copy-mail-2': 'E-mail copié !',
        ':alert-copy-mail-3': 'E-mail copié !',
        ':buy-cellesti-token': 'Acheter le Token Cellesti',
        ':stage': 'Étape 1',
        ':next-stage-value': '1 CLLS = 0,007 $ et Étape Suivante = 0,00875 $',
        ':tokens-sold': 'TOKENS VENDUS',
        ':usd-raised': 'USD RÉCOLTÉS',
        ':bonus': 'Bonus',
        ':payment-method': 'Méthode de Paiement',
        ':buy-with-eth': 'ACHETER AVEC ETH',
        ':buy-with-usdt': 'ACHETER AVEC USDT',
        ':choose': 'fr',
        ':how-to-buy': 'Comment Acheter ?',
        ':buy-button': 'Acheter',
        ':buy-button-2': 'Acheter',
        ':buy-button-3': 'Acheter',
        ':approve': 'Approuver',
        ':clls-token': 'LE TOKEN $CLLS',
        ':clls-token-paragraph-1': 'Cellesti est une plateforme révolutionnaire qui permet d\'investir dans des startups d\'IA en utilisant $CLLS, notre cryptomonnaie innovante. Grâce à notre système d\'investissement fractionné, nous offrons la possibilité de soutenir des startups d\'IA prometteuses via des NFTs (Jetons Non Fongibles), transformant chaque opportunité en un actif numérique unique.',
        ':clls-token-paragraph-2': 'Cela vous permet d\'investir en fonction de votre capacité financière, tout en profitant des avantages d\'être un soutien précoce des technologies émergentes. Cellesti rend l\'investissement simple, sécurisé et percutant, vous offrant l\'opportunité de participer activement à l\'innovation technologique et de récolter les fruits en tant qu\'investisseur précoce.',
        ':why-choose-us-card-1-title': 'Investissement Sans Effort',
        ':why-choose-us-card-1-text': 'Investir dans des startups d\'IA de pointe n\'a jamais été aussi accessible. Avec notre plateforme fluide et intuitive, tout le monde—que vous soyez un investisseur expérimenté ou que vous débutiez—peut facilement naviguer et commencer à investir dans l\'avenir de la technologie IA.',
        ':why-choose-us-card-2-title': 'Sécurité Avancée',
        ':why-choose-us-card-2-text': 'Votre confiance et votre sécurité sont nos principales priorités chez Cellesti. Nous utilisons une technologie blockchain avancée pour garder vos investissements en sécurité, avec un chiffrement de haut niveau et des systèmes décentralisés qui garantissent un environnement hautement sécurisé.',
        ':why-choose-us-card-3-title': 'Révolutionner l\'Investissement',
        ':why-choose-us-card-3-text': 'Débloquez de nouvelles opportunités avec notre système d\'investissement fractionné, en acquérant une part de propriété dans des startups d\'IA auparavant inaccessibles grâce à l\'innovation de la tokenisation des NFTs.',
        ':why-choose-us-card-4-title': 'Opportunités d\'Investissement Élargies',
        ':why-choose-us-card-4-text': 'Élargissez votre champ d\'investissement en diversifiant facilement votre portefeuille d\'IA. Découvrez des startups à chaque étape et alignez vos investissements avec vos objectifs financiers en toute simplicité.',
        ":why-choose-us-card-5-title": "Récompenses Pionnières pour les Premiers Sostenants",
        ":why-choose-us-card-5-text": "Soyez un pionnier de l'innovation technologique, en profitant d'avantages et d'aperçus exclusifs en tant que premier soutien, préparant le terrain pour de futurs gains potentiels.",
        ":why-choose-us-card-6-title": "Restez en Avance avec le Suivi en Direct",
        ":why-choose-us-card-6-text": "Utilisez notre tableau de bord simple pour suivre vos investissements en temps réel. Prenez des décisions stratégiques dans le secteur de l'IA en pleine évolution.",
        ":ai-action-title": "REJOIGNEZ NOTRE COMMUNAUTÉ",
        ":ai-action-subtitle": "Finances Intelligentes Avec Cellesti",
        ":ai-action-descript": "Rejoignez notre projet, animé par l'innovation, la communauté et notre vision de l'IA. Achetez, vendez et échangez facilement dans notre écosystème décentralisé. Devenez membre de notre communauté IA.",
        ":read-more": "Lire la suite",
        ":powered-by": "Alimenté Par :",
        ":claim-your-tokens": "RÉCLAMEZ VOS JETONS",
        ":see-tokens-button": "Voir Vos Jetons Réclamables",
        ":claimable-tokens": "Jetons Réclamables",
        ":bonus-tokens": "Jetons Bonus",
        ":staking-text": "En stakant des jetons $CLLS, les investisseurs peuvent gagner des récompenses provenant de notre taxe de vente de 10%, qui est allouée à un fonds de récompenses dédié. Le mécanisme de staking offre une occasion unique à notre communauté de gagner des récompenses en jetons $CLLS tout en contribuant à la croissance des startups technologiques d'IA.",
        ":percents-text-1": "Vente Publique",
        ":percents-text-2": "Équipe de Développement",
        ":percents-text-lock": "3 ans verrouillés",
        ":percents-text-3": "LP + Liste d'Échanges + Pool de Récompenses",
        ":percents-text-5": "Juridique et Conseillers",
        ":notebook-title": "GOUVERNANCE",
        ":notebook-text": "Le jeton $CLLS permet aux détenteurs de participer activement à la prise de décision de la plateforme. En proposant, discutant et votant sur des questions clés, ils contribuent à façonner l'avenir de la plateforme. Cette approche axée sur la communauté soutient la croissance des startups d'IA tout en promouvant un écosystème plus collaboratif.",
        ":giveaway-title": "PARTAGEZ LE CONCOURS !",
        ":giveaway-text-part-a": "Prêt à gagner gros ? Participez au grand",
        ":giveaway-text-part-b": "Tirage au Sort de la Tesla Model S",
        ":giveaway-text-part-c": "Participez et complétez toutes les participations pour avoir une chance de gagner le grand prix. Ne manquez pas votre chance d'être le gagnant chanceux !",
        ":giveaway-button": "JOUONS AU TIRAGE AU SORT",
        ":ai-startups-title": "START-UPS D'IA, POSTULEZ",
        ":ai-startups-text-1": "Êtes-vous une start-up d'IA cherchant à lever des fonds et à interagir avec votre communauté ?",
        ":ai-startups-text-2": "Notre marketplace NFT offre une plateforme innovante pour créer des opportunités d'investissement, reliant une communauté dédiée d'investisseurs engagés à faire progresser la technologie de l'IA. Grâce à cette marketplace, les investisseurs peuvent accéder à des options d'investissement uniques tout en soutenant la croissance et le développement de startups d'IA de pointe.",
        ":ai-startups-buttons-apply": "Postuler",
        ":ai-startups-buttons-buy": "Acheter $CLLS",
        ":faqs-title": "Vous avez peut-être des questions, nous avons les réponses.",
        ":faq-heading-1": "Qu'est-ce que le TOKEN Cellesti ?",
        ":faq-text-1": "Cellesti est une plateforme de financement participatif NFT en crypto qui permet aux utilisateurs d'investir dans des projets de start-up d'IA en utilisant des devises fiat et des cryptomonnaies. Le marketplace NFT permet aux start-ups de lever des fonds et d'interagir avec leur communauté en offrant des NFTs basés sur des récompenses et des actions.",
        ":faq-heading-2": "Comment acheter le token Cellesti lors de la prévente ?",
        ":faq-text-2": "Les tokens $CLLS peuvent être achetés pendant la période de prévente via le site Web de Cellesti en utilisant ETH, USDT, BTC et de nombreuses autres cryptomonnaies prises en charge.",
        ":faq-heading-3": "Sur quel réseau Blockchain se trouve le token Cellesti ?",
        ":faq-text-3": "Cellesti est construit sur Ethereum (ETH), tirant parti de sa vitesse, de sa convivialité et de sa compatibilité avec les applications décentralisées pour créer une expérience utilisateur sans faille.",
        ":faq-heading-4": "Comment réclamer mes tokens ?",
        ":faq-text-4": "Une fois la prévente terminée, vous devez simplement connecter votre portefeuille et appuyer sur le bouton de réclamation. Une fois la transaction terminée, importez l'adresse du token Cellesti dans votre portefeuille et vous pourrez voir vos tokens.",
        ":faq-heading-5": "Comment puis-je stocker et gérer mes tokens Cellesti ?",
        ":faq-text-5": "Les tokens Cellesti peuvent être stockés et gérés dans des portefeuilles de cryptomonnaies compatibles. Nous recommandons d'utiliser des portefeuilles qui prennent en charge Ethereum, tels que MetaMask ou Trust Wallet.",
        ':copyright': "Copyright © 2024. Tous droits réservés à Cellesti.",
        ':disclaimer-title': "Avertissement",
        ':disclaimer-text': "Les investissements en cryptomonnaies présentent un risque élevé de volatilité. Soyez conscient des implications fiscales, car les bénéfices peuvent être soumis à des impôts sur les gains en capital ou d'autres taxes dans votre juridiction. Les réglementations sur les cryptomonnaies peuvent varier, alors assurez-vous de comprendre les règles dans votre région. Effectuez des recherches approfondies et n'investissez que ce que vous pouvez vous permettre de perdre.",
        ':our-socials-title': "Nos réseaux sociaux"
    },
    'de': {
        ':title' : 'Die Vorverkaufsaktion Ist Aktiv',
        ':menu-home': 'Zuhause',
        ':menu-why-choose-us': 'Warum uns wählen?',
        ':menu-token-details': 'Token-Details',
        ':whitepaper': 'Weißes Papier',
        ':connect-wallet': 'Wallet verbinden',
        ':connect': 'Wallet verbinden',
        ':apresentation-h5': 'Nehmen Sie an der Vorverkaufsveranstaltung teil',
        ':apresentation-h1': 'Investieren Sie in die Zukunft der KI-Technologie mit Cellesti',
        ':apresentation-h7': 'Investieren Sie einfach in KI-Startups mit fractional Tokens und seien Sie Teil der nächsten technischen Revolution.',
        ':apresentation-paragraph-1': 'KI-gestützte Investitionen unterstützen einige der vielversprechendsten KI-Startups weltweit.',
        ':apresentation-paragraph-2': 'Fractionale NFTs: Investieren Sie entsprechend Ihrem Budget und erhalten Sie Eigentum an aufregenden Whitepaper-Projekten.',
        ':alert-copy-mail': 'E-Mail kopiert!',
        ':alert-copy-mail-2': 'E-Mail kopiert!',
        ':alert-copy-mail-3': 'E-Mail kopiert!',
        ':buy-cellesti-token': 'Cellesti Token kaufen',
        ':stage': 'Stufe 1',
        ':next-stage-value': '1 CLLS = 0,007 $ & Nächste Stufe = 0,00875 $',
        ':tokens-sold': 'VERKAUFTE TOKENS',
        ':usd-raised': 'USD EINGENOMMEN',
        ':bonus': 'Bonus',
        ':payment-method': 'Zahlungsmethode',
        ':buy-with-eth': 'MIT ETH KAUFEN',
        ':buy-with-usdt': 'MIT USDT KAUFEN',
        ':choose': 'de',
        ':how-to-buy': 'Wie Kaufen?',
        ':buy-button': 'Kaufen',
        ':buy-button-2': 'Kaufen',
        ':buy-button-3': 'Kaufen',
        ':approve': 'Genehmigen',
        ':clls-token': 'DER $CLLS TOKEN',
        ':clls-token-paragraph-1': 'Cellesti ist eine bahnbrechende Plattform, die Investitionen in KI-Startups mit $CLLS, unserer innovativen Kryptowährung, ermöglicht. Durch unser System für fraktionierte Investitionen bieten wir die Möglichkeit, vielversprechende KI-Startups über NFTs (Nicht-fungible Tokens) zu unterstützen und jede Gelegenheit in einen einzigartigen digitalen Vermögenswert zu verwandeln.',
        ':clls-token-paragraph-2': 'Dies ermöglicht es Ihnen, entsprechend Ihrer finanziellen Kapazität zu investieren, während Sie die Vorteile genießen, ein früher Unterstützer aufstrebender Technologien zu sein. Cellesti macht Investieren einfach, sicher und wirkungsvoll, indem es Ihnen die Möglichkeit gibt, aktiv an technologischer Innovation teilzunehmen und die Belohnungen als Frühinvestor zu ernten.',
        ':why-choose-us-card-1-title': 'Müheloses Investieren',
        ':why-choose-us-card-1-text': 'Investieren in moderne KI-Startups war noch nie so zugänglich. Mit unserer nahtlosen und intuitiven Plattform kann jeder—egal, ob Sie ein erfahrener Investor sind oder gerade erst anfangen—einfach navigieren und in die Zukunft der KI-Technologie investieren.',
        ':why-choose-us-card-2-title': 'Fortschrittliche Sicherheit',
        ':why-choose-us-card-2-text': 'Ihr Vertrauen und Ihre Sicherheit haben bei Cellesti oberste Priorität. Wir nutzen fortschrittliche Blockchain-Technologie, um Ihre Investitionen zu sichern, mit erstklassiger Verschlüsselung und dezentralisierten Systemen, die eine hochsichere Umgebung gewährleisten.',
        ':why-choose-us-card-3-title': 'Investitionen Revolutionieren',
        ':why-choose-us-card-3-text': 'Entsperren Sie neue Möglichkeiten mit unserem System für fraktionierte Investitionen und erwerben Sie Eigentum an zuvor unzugänglichen KI-Startups durch innovative NFT-Tokenisierung.',
        ':why-choose-us-card-4-title': 'Umfangreiche Investitionsmöglichkeiten',
        ':why-choose-us-card-4-text': 'Erweitern Sie Ihren Investitionsbereich, indem Sie Ihr KI-Portfolio ganz einfach diversifizieren. Entdecken Sie Startups in allen Phasen und stimmen Sie Ihre Investitionen mühelos auf Ihre finanziellen Ziele ab.',
        ":why-choose-us-card-5-title": "Pionierhafte Belohnungen für Frühe Unterstützer",
        ":why-choose-us-card-5-text": "Seien Sie ein Pionier in der technologischen Innovation und genießen Sie exklusive Vorteile und Einblicke als früher Unterstützer, der den Grundstein für potenzielle zukünftige Gewinne legt.",
        ":why-choose-us-card-6-title": "Bleiben Sie Vorne mit Live-Überwachung",
        ":why-choose-us-card-6-text": "Nutzen Sie unser einfaches Dashboard, um Ihre Investitionen in Echtzeit zu überwachen. Treffen Sie strategische Entscheidungen im schnelllebigen KI-Sektor.",
        ":ai-action-title": "TRETEN SIE UNSERER GEMEINSCHAFT BEI",
        ":ai-action-subtitle": "Intelligente Finanzen Mit Cellesti",
        ":ai-action-descript": "Treten Sie unserem Projekt bei, das von Innovation, Gemeinschaft und unserer KI-Vision angetrieben wird. Kaufen, verkaufen und tauschen Sie einfach in unserem dezentralen Ökosystem. Werden Sie Mitglied unserer KI-Community.",
        ":read-more": "Mehr lesen",
        ":powered-by": "Bereitgestellt Von:",
        ":claim-your-tokens": "FORDERN SIE IHRE TOKEN AN",
        ":see-tokens-button": "Sehen Sie Ihre Anspruchbaren Token",
        ":claimable-tokens": "Anspruchbare Token",
        ":bonus-tokens": "Bonus-Token",
        ":staking-text": "Durch das Staken von $CLLS-Token können Investoren Belohnungen aus unserer 10%-Verkaufssteuer verdienen, die einem speziellen Belohnungspool zugewiesen ist. Der Staking-Mechanismus bietet unserer Gemeinschaft eine einzigartige Möglichkeit, $CLLS-Token-Belohnungen zu verdienen, während sie das Wachstum von KI-Technologie-Startups unterstützt.",
        ":percents-text-1": "Öffentlicher Verkauf",
        ":percents-text-2": "Entwicklungsteam",
        ":percents-text-lock": "3 Jahre gesperrt",
        ":percents-text-3": "LP + Börsennotierung + Belohnungspool",
        ":percents-text-5": "Rechtlich & Berater",
        ":notebook-title": "GOVERNANCE",
        ":notebook-text": "Der $CLLS-Token befähigt die Inhaber, aktiv an der Entscheidungsfindung der Plattform teilzunehmen. Indem sie über wichtige Themen Vorschläge machen, diskutieren und abstimmen, helfen sie, die Zukunft der Plattform zu gestalten. Dieser gemeinschaftsorientierte Ansatz unterstützt das Wachstum von KI-Startups und fördert ein kooperativeres Ökosystem.",
        ":giveaway-title": "NEHMEN SIE AM GEWINNSPIEL TEIL!",
        ":giveaway-text-part-a": "Bereit, groß zu gewinnen? Nehmen Sie am großen",
        ":giveaway-text-part-b": "Tesla Model S Verlosung",
        ":giveaway-text-part-c": "Nehmen Sie teil und vervollständigen Sie alle Einträge für Ihre Chance, den Hauptpreis zu gewinnen. Verpassen Sie nicht Ihre Chance, der glückliche Gewinner zu sein!",
        ":giveaway-button": "LASST UNS DAS GEWINNSPIEL SPIELEN",
        ":ai-startups-title": "KI-STARTUPS BEWERBEN SICH",
        ":ai-startups-text-1": "Sind Sie ein KI-Start-up, das Mittel beschaffen und mit Ihrer Gemeinschaft interagieren möchte?",
        ":ai-startups-text-2": "Unser NFT-Marktplatz bietet eine innovative Plattform zur Schaffung von Investitionsmöglichkeiten und verbindet eine engagierte Gemeinschaft von Investoren, die sich der Förderung der KI-Technologie verschrieben haben. Durch diesen Marktplatz können Investoren auf einzigartige Investitionsmöglichkeiten zugreifen und gleichzeitig das Wachstum und die Entwicklung von hochmodernen KI-Startups unterstützen.",
        ":ai-startups-buttons-apply": "Bewerben",
        ":ai-startups-buttons-buy": "Kaufe $CLLS",
        ":faqs-title": "Sie haben vielleicht Fragen, wir haben die Antworten.",
        ":faq-heading-1": "Was ist der Cellesti TOKEN?",
        ":faq-text-1": "Cellesti ist eine Krypto-Crowdfunding-NFT-Plattform, die es Benutzern ermöglicht, in KI-Start-up-Projekte mit Fiat- und Krypto-Währungen zu investieren. Der NFT-Marktplatz ermöglicht es Start-ups, Mittel zu beschaffen und mit ihrer Gemeinschaft zu interagieren, indem sie NFTs anbieten, die auf Belohnungen und Eigenkapital basieren.",
        ":faq-heading-2": "Wie kaufe ich den Cellesti-Token in der Vorverkaufsphase?",
        ":faq-text-2": "$CLLS-Token können während des Vorverkaufszeitraums über die Cellesti-Website mit ETH, USDT, BTC und vielen weiteren unterstützten Kryptowährungen gekauft werden.",
        ":faq-heading-3": "Auf welchem Blockchain-Netzwerk ist der Cellesti-Token?",
        ":faq-text-3": "Cellesti basiert auf Ethereum (ETH) und nutzt dessen Geschwindigkeit, Benutzerfreundlichkeit und Kompatibilität mit dezentralen Anwendungen, um ein nahtloses Benutzererlebnis zu schaffen.",
        ":faq-heading-4": "Wie fordere ich meine Tokens an?",
        ":faq-text-4": "Sobald der Vorverkauf endet, müssen Sie nur noch Ihre Wallet verbinden und die Schaltfläche „Token beanspruchen“ drücken. Sobald die Transaktion abgeschlossen ist, importieren Sie die Cellesti-Token-Adresse in Ihre Wallet, und Sie können Ihre Tokens sehen.",
        ":faq-heading-5": "Wie kann ich meine Cellesti-Token speichern und verwalten?",
        ":faq-text-5": "Cellesti-Token können in kompatiblen Kryptowährungs-Wallets gespeichert und verwaltet werden. Wir empfehlen die Verwendung von Wallets, die Ethereum unterstützen, wie MetaMask oder Trust Wallet.",
        ':copyright': "Urheberrecht © 2024. Alle Rechte vorbehalten für Cellesti.",
        ':disclaimer-title': "Haftungsausschluss",
        ':disclaimer-text': "Investitionen in Kryptowährungen bergen ein hohes Risiko der Volatilität. Seien Sie sich der steuerlichen Auswirkungen bewusst, da Gewinne möglicherweise der Kapitalertragssteuer oder anderen Steuern in Ihrer Gerichtsbarkeit unterliegen. Die Vorschriften für Kryptowährungen können variieren, daher sollten Sie die Regeln in Ihrem Bereich verstehen. Führen Sie gründliche Recherchen durch und investieren Sie nur das, was Sie sich leisten können zu verlieren.",
        ':our-socials-title': "Unsere sozialen Medien"
    },
    'es': {
        ':title' : 'La Preventa Está Activa',
        ':menu-home': 'Inicio',
        ':menu-why-choose-us': '¿Por qué elegirnos?',
        ':menu-token-details': 'Detalles del Token',
        ':whitepaper': 'Libro Blanco',
        ':connect-wallet': 'Conectar Billetera',
        ':connect': 'Conectar Billetera',
        ':apresentation-h5': 'Únete a la Preventa',
        ':apresentation-h1': 'Invierte en el Futuro de la Tecnología de IA con Cellesti',
        ':apresentation-h7': 'Invierte fácilmente en startups de IA con tokens fraccionarios y sé parte de la próxima revolución tecnológica.',
        ':apresentation-paragraph-1': 'Las inversiones impulsadas por IA apoyan algunas de las startups de IA más prometedoras en todo el mundo.',
        ':apresentation-paragraph-2': 'NFTs fraccionarios: Invierte de acuerdo a tu presupuesto y recibe propiedad en emocionantes proyectos del libro blanco.',
        ':alert-copy-mail': '¡Correo electrónico copiado!',
        ':alert-copy-mail-2': '¡Correo electrónico copiado!',
        ':alert-copy-mail-3': '¡Correo electrónico copiado!',
        ':buy-cellesti-token': 'Comprar Token Cellesti',
        ':stage': 'Etapa 1',
        ':next-stage-value': '1 CLLS = $0.007 y Siguiente Etapa = $0.00875',
        ':tokens-sold': 'TOKENS VENDIDOS',
        ':usd-raised': 'USD RECAUDADOS',
        ':bonus': 'Bono',
        ':payment-method': 'Método de Pago',
        ':buy-with-eth': 'COMPRAR CON ETH',
        ':buy-with-usdt': 'COMPRAR CON USDT',
        ':choose': 'es',
        ':how-to-buy': '¿Cómo Comprar?',
        ':buy-button': 'Comprar',
        ':buy-button-2': 'Comprar',
        ':buy-button-3': 'Comprar',
        ':approve': 'Aprobar',
        ':clls-token': 'EL TOKEN $CLLS',
        ':clls-token-paragraph-1': 'Cellesti es una plataforma innovadora que permite inversiones en startups de IA utilizando $CLLS, nuestra criptomoneda innovadora. A través de nuestro sistema de inversión fraccionaria, ofrecemos la oportunidad de apoyar a startups de IA prometedoras a través de NFTs (Tokens No Fungibles), convirtiendo cada oportunidad en un activo digital único.',
        ':clls-token-paragraph-2': 'Esto te permite invertir de acuerdo a tu capacidad financiera, mientras disfrutas de las ventajas de ser un apoyo temprano de tecnologías emergentes. Cellesti hace que invertir sea simple, seguro e impactante, dándote la oportunidad de participar activamente en la innovación tecnológica y cosechar las recompensas como un inversor temprano.',
        ':why-choose-us-card-1-title': 'Inversión Sin Esfuerzo',
        ':why-choose-us-card-1-text': 'Invertir en startups de IA de vanguardia nunca ha sido tan accesible. Con nuestra plataforma intuitiva y sin complicaciones, cualquiera—ya sea un inversionista experimentado o que apenas comienza—puede navegar fácilmente y comenzar a invertir en el futuro de la tecnología de IA.',
        ':why-choose-us-card-2-title': 'Seguridad Avanzada',
        ':why-choose-us-card-2-text': 'Su confianza y seguridad son nuestras principales prioridades en Cellesti. Utilizamos tecnología blockchain avanzada para mantener seguros sus inversiones, con encriptación de alto nivel y sistemas descentralizados que garantizan un entorno altamente seguro.',
        ':why-choose-us-card-3-title': 'Revolucionando la Inversión',
        ':why-choose-us-card-3-text': 'Desbloquea nuevas oportunidades con nuestro sistema de inversión fraccionaria, obteniendo propiedad en startups de IA previamente inaccesibles a través de la tokenización innovadora de NFTs.',
        ':why-choose-us-card-4-title': 'Oportunidades de Inversión Expansivas',
        ':why-choose-us-card-4-text': 'Amplía tu ámbito de inversión diversificando fácilmente tu cartera de IA. Descubre startups en cada etapa y alinea tus inversiones con tus objetivos financieros con facilidad.',
        ":why-choose-us-card-5-title": "Recompensas Pioneras para los Primeros Apoyadores",
        ":why-choose-us-card-5-text": "Sé un pionero en la innovación tecnológica, disfrutando de beneficios e insights exclusivos como un apoyo temprano, preparando el escenario para posibles ganancias futuras.",
        ":why-choose-us-card-6-title": "Mantente Adelante con Monitoreo en Vivo",
        ":why-choose-us-card-6-text": "Usa nuestro panel simple para monitorear tus inversiones en tiempo real. Toma decisiones estratégicas en el sector de IA en rápida evolución.",
        ":ai-action-title": "ÚNETE A NUESTRA COMUNIDAD",
        ":ai-action-subtitle": "Finanzas Inteligentes Con Cellesti",
        ":ai-action-descript": "Únete a nuestro proyecto, impulsado por la innovación, la comunidad y nuestra visión de IA. Compra, vende e intercambia fácilmente en nuestro ecosistema descentralizado. Conviértete en miembro de nuestra comunidad de IA.",
        ":read-more": "Leer más",
        ":powered-by": "Impulsado Por:",
        ":claim-your-tokens": "RECLAMA TUS TOKENS",
        ":see-tokens-button": "Ver Tus Tokens Reclamables",
        ":claimable-tokens": "Tokens Reclamables",
        ":bonus-tokens": "Tokens de Bonificación",
        ":staking-text": "Al hacer staking de tokens $CLLS, los inversores pueden ganar recompensas de nuestro impuesto de venta del 10%, que se destina a un fondo de recompensas dedicado. El mecanismo de staking ofrece una oportunidad única para que nuestra comunidad gane recompensas en tokens $CLLS mientras ayuda a impulsar el crecimiento de startups de tecnología de IA.",
        ":percents-text-1": "Venta Pública",
        ":percents-text-2": "Equipo de Desarrollo",
        ":percents-text-lock": "3 años bloqueados",
        ":percents-text-3": "LP + Listado en Exchanges + Fondo de Recompensas",
        ":percents-text-5": "Legal y Asesores",
        ":notebook-title": "GOBERNANZA",
        ":notebook-text": "El token $CLLS empodera a los titulares para participar activamente en la toma de decisiones de la plataforma. Al proponer, discutir y votar sobre temas clave, ayudan a dar forma al futuro de la plataforma. Este enfoque impulsado por la comunidad apoya el crecimiento de startups de IA mientras promueve un ecosistema más colaborativo.",
        ":giveaway-title": "¡ÚNETE AL SORTEO!",
        ":giveaway-text-part-a": "¿Listo para ganar a lo grande? Participa en el gran",
        ":giveaway-text-part-b": "Sorteo del Tesla Model S",
        ":giveaway-text-part-c": "¡Participa y completa todas las entradas para tener la oportunidad de ganar el gran premio! ¡No te pierdas la oportunidad de ser el afortunado ganador!",
        ":giveaway-button": "JUGUEMOS A LA RIFA",
        ":ai-startups-title": "STARTUPS DE IA APLIQUEN",
        ":ai-startups-text-1": "¿Eres una startup de IA que busca recaudar fondos y relacionarse con su comunidad?",
        ":ai-startups-text-2": "Nuestro marketplace de NFT ofrece una plataforma innovadora para crear oportunidades de inversión, conectando a una comunidad dedicada de inversores comprometidos con el avance de la tecnología de IA. A través de este marketplace, los inversores pueden acceder a opciones de inversión únicas mientras apoyan el crecimiento y desarrollo de startups de IA de vanguardia.",
        ":ai-startups-buttons-apply": "Aplicar",
        ":ai-startups-buttons-buy": "Comprar $CLLS",
        ":faqs-title": "Puede que tengas preguntas, nosotros tenemos las respuestas.",
        ":faq-heading-1": "¿Qué es el TOKEN Cellesti?",
        ":faq-text-1": "Cellesti es una plataforma de crowdfunding NFT de criptomonedas que permite a los usuarios invertir en proyectos de startups de IA utilizando Fiat y Cripto. El marketplace de NFT permite a las startups recaudar fondos y relacionarse con su comunidad ofreciendo NFTs basados en recompensas y acciones.",
        ":faq-heading-2": "¿Cómo compro el token Cellesti en la preventa?",
        ":faq-text-2": "Los tokens $CLLS se pueden adquirir durante el período de preventa a través del sitio web de Cellesti utilizando ETH, USDT, BTC y muchas otras criptomonedas admitidas.",
        ":faq-heading-3": "¿En qué red Blockchain está el token Cellesti?",
        ":faq-text-3": "Cellesti está construido en Ethereum (ETH), aprovechando su velocidad, usabilidad y compatibilidad con aplicaciones descentralizadas para crear una experiencia de usuario sin problemas.",
        ":faq-heading-4": "¿Cómo reclamo mis tokens?",
        ":faq-text-4": "Una vez que finalice la preventa, solo necesitas conectar tu billetera y presionar el botón de reclamar. Una vez que la transacción esté completa, importa la dirección del token Cellesti en tu billetera y podrás ver tus tokens.",
        ":faq-heading-5": "¿Cómo puedo almacenar y gestionar mis tokens Cellesti?",
        ":faq-text-5": "Los tokens Cellesti se pueden almacenar y gestionar en billeteras de criptomonedas compatibles. Recomendamos usar billeteras que soporten Ethereum, como MetaMask o Trust Wallet.",
        ':copyright': "Copyright © 2024. Todos los derechos reservados por Cellesti.",
        ':disclaimer-title': "Descargo de responsabilidad",
        ':disclaimer-text': "Las inversiones en criptomonedas conllevan un alto riesgo de volatilidad. Tenga en cuenta las implicaciones fiscales, ya que las ganancias pueden estar sujetas a impuestos sobre ganancias de capital u otros impuestos en su jurisdicción. Las regulaciones de criptomonedas pueden variar, así que asegúrese de comprender las reglas en su área. Realice una investigación exhaustiva e invierta solo lo que pueda permitirse perder.",
        ':our-socials-title': "Nuestras redes sociales"
    }
}
